# Generated by Django 4.0.6 on 2022-07-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSEAsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pse', models.BigIntegerField()),
                ('nomor_pb_umku', models.IntegerField(blank=True, null=True)),
                ('nama', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_perusahaan', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_daftar', models.DateField(blank=True, null=True)),
                ('nomor_tanda_daftar', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sistem_elektronik_id', models.BigIntegerField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PSE Asing',
                'verbose_name_plural': 'PSE Asing',
            },
        ),
        migrations.CreateModel(
            name='PSELokal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pse', models.BigIntegerField()),
                ('nomor_pb_umku', models.IntegerField(blank=True, null=True)),
                ('nama', models.CharField(max_length=255)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_perusahaan', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_daftar', models.DateField(blank=True, null=True)),
                ('nomor_tanda_daftar', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sistem_elektronik_id', models.BigIntegerField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PSE Lokal',
                'verbose_name_plural': 'PSE Lokal',
            },
        ),
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektor',
            },
        ),
        migrations.CreateModel(
            name='PSELokalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='monitor.pselokal')),
            ],
        ),
        migrations.AddField(
            model_name='pselokal',
            name='sektor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perusahaanlokal', to='monitor.sektor'),
        ),
        migrations.CreateModel(
            name='PSEAsingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='monitor.pseasing')),
            ],
        ),
        migrations.AddField(
            model_name='pseasing',
            name='sektor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perusahaanasing', to='monitor.sektor'),
        ),
    ]
