# Generated by Django 4.0.6 on 2022-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseasing',
            name='nomor_pb_umku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pselokal',
            name='nomor_pb_umku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
