# Generated by Django 4.0.6 on 2022-07-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_pseasing_nomor_pb_umku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pseasing',
            name='sektor',
        ),
        migrations.AddField(
            model_name='pseasing',
            name='sektor',
            field=models.ManyToManyField(related_name='perusahaanasing', to='monitor.sektor'),
        ),
        migrations.RemoveField(
            model_name='pselokal',
            name='sektor',
        ),
        migrations.AddField(
            model_name='pselokal',
            name='sektor',
            field=models.ManyToManyField(related_name='perusahaanlokal', to='monitor.sektor'),
        ),
    ]
